### ISSUE TITLE
Make  error on centos 7

### ISSUE THREAD

**Issue by m1cka** [dimitri/pgcharts#10]
when i try use 'make' i get  error
```
Fatal SIMPLE-ERROR:
  This SBCL does not support core compression
make: *** [build/bin/pgcharts] Error 1
version SBCL 1.2.8-1.el7
```

then found this 'make COMPRESS_CORE=no' there is no error, but then when i tried 
```
./pgcharts start or pgcharts setup pgsql://localhost/pgcharts
error:
Installing pgcharts database model.
ERROR: Database error 42601: syntax error at or near "not"
QUERY: ---
--- pgcharts model
---
create schema if not exists pgcharts
```

i tried to edit model.sql file,created schema manualy. bet error the same.

any idea?

**Comment by dimitri** [comment]
Sounds like you're using a PostgreSQL version that is before 9.3:

  http://www.postgresql.org/docs/9.2/static/sql-createschema.html
  http://www.postgresql.org/docs/9.3/static/sql-createschema.html

Best would be to adapt the SQL to work on previous PostgreSQL versions (9.0, 9.1 and 9.2 are not to be deprecated before long). 

When you edit the SQL files, you need to recompile pgcharts. So please remove the `if not exists` parts in the create schema and report back?

**Comment by m1cka** [comment]
after recompilate,  model.sql  inserted, but then updating '20140823--20140828.sql'  and get error 
ERROR:  column "dbuser" does not exist
LINE 3:                     || coalesce(dbuser, '')

then i checked  db table, and it was empty. so i put data using
insert INTO pgcharts.db (dbname, dburi) values ('pgcharts', 'pgsql://pgcharts:pgcharts@localhost/pgcharts');

after this  insert- working.

**Comment by dimitri** [comment]
There's something fishy here because I don't see why your model would have had to be updated, given it's a very recent install. It should have been directly installed with the correct version. So I guess your manual fiddling with the model had the version detection wrong or something. Glad it's now working!

**Comment by m1cka** [comment]
tnx for help
