### ISSUE TITLE
Documentation for newbie

### ISSUE THREAD

**Issue by waghanza** [dimitri/pgcharts#12]
Hello,

I discover pgchart, this app fit to my needs (I thinks).
However, I do not know **how** to use it.

I have two table, 
- products : id, name, provider_id
- providers : id, name

I want to display a **pie** chart listing number of **products** per **providers**.

``` sql
select count(pr.id), pv.name from products as pr left join providers as pv on pv.id = pr.provider_id
```

How can I do that ? 

Regards,

**Comment by dimitri** [comment]
When you run the pgcharts application, it listens on http on the port 9042 by default. Connect your web browser to http://localhost:9042/ and you will be able to create a new query chart from the UI. I'm not sure to understand your question, really. Please detail what you did?

**Comment by waghanza** [comment]
I want to build a **pie chart** following the previous specs.
I have the right sql query (result are ok), but I do not understand what query have I to use to build a **pie chart**
