### ISSUE TITLE
Is there any access levels managements ?

### ISSUE THREAD

**Issue by waghanza** [dimitri/pgcharts#13]
Hi,

Expected to visualize my data, I find that `pgcharts` fits to my needs :+1: 

This app is made to run for one person only, I presume ? or is there any team access levels ?

Regards,

**Comment by dimitri** [comment]
At the moment there's no access levels other than what you have already with PostgreSQL. The idea is that the admin does register the databases connections and the web user can only query into those connections, that contains the login role used, and you can limit what this role may do at the PostgreSQL level.
