### ISSUE TITLE
README doesn't point to the right link

### ISSUE THREAD

**Issue by jsjolen** [dimitri/pgcharts#16]
Hi :-)!

The link to http://packages.debian.org/search?keywords=sbcl becomes a link to /blob/master of this repo, signalling a 404.
Suggested fix: 

[http://packages.debian.org/search?keywords=sbcl]()  -> [http://packages.debian.org/search?keywords=sbcl](http://packages.debian.org/search?keywords=sbcl)

Same goes for the link to your backport link.

**Comment by dimitri** [comment]
Hi, can you edit a pull request please? Thanks!

**Comment by jsjolen** [comment]
Hi, sorry for the late response.
I'll take care of that later today (in 8hrs or so).
