### ISSUE TITLE
Queries which return null values break charts

### ISSUE THREAD

**Issue by realark** [dimitri/pgcharts#19]
Root cause appears to be an attempt to pass `:null` (a keyword name null) to `yason:encode`. Can I get your thoughts on this? Is this an acceptable solution? I'm happy to create a PR.

# Reproduce
1. Create a query which will return null for some values.
2. Run Query. Charts will not show and error will appear in logs
```
#<STANDARD-GENERIC-FUNCTION YASON:ENCODE (13)>
when called with arguments
(:NULL
 #<SB-IMPL::STRING-OUTPUT-STREAM>)
```

# Potential Fix
Defining a dispatcher on :null does the trick:
```
(defmethod yason:encode ((object (eql :null))
                         &optional (stream *standard-output*))
  (format stream "null"))
```

**Comment by dimitri** [comment]
Hi! I'm in very low maintenance for pgcharts. I'm very happy that it works for you and will happily accept a PR. Do you want to help maintaining and improving pgcharts?

**Comment by realark** [comment]
Great, I'll submit a PR. Yes, I'd love to help out maintaining pgcharts.

**Comment by dimitri** [comment]
I've added you as a collaborator on the project, so you should have received an invite from GitHub. One you've accepted it, please push your fix directly to the main repository! Thanks a lot,

**Comment by realark** [comment]
Thanks!
