### ISSUE TITLE
Install on centos6

### ISSUE THREAD

**Issue by Jacob-Kroeze** [dimitri/pgcharts#7]
To install on centos6, I used  your bootstrap-centos.sh from dimitri/pgloader in order to install sbcl.
https://github.com/dimitri/pgloader/blob/master/bootstrap-centos.sh

I tried
    `$ install`
    `$ sbcl --version` 
    `#> SBCL 1.1.14`
And got a UIOP missing error from quicklisp.
    `$ make clean all`
    `$ install`

..."make clean all" worked in the end to pull in UIOP. I don't know why this works.

**Comment by dimitri** [comment]
Quicklisp will install its own version of ASDF if the one provided by the implementation (here, SBCL) is too old, so I think that's why it worked the second time. Just note that 1.1.14 is very old now.
