### ISSUE TITLE
pgcharts.1 reference to server reload command does not exist

### ISSUE THREAD

**Issue by Jacob-Kroeze** [dimitri/pgcharts#8]
<code>$ pgcharts server reload
pgcharts [ --help ] [ --version ] [ --config filename ] command ...
pgcharts: command line parse error.
Error parsing args: "server" "reload"
</code>

    Available commands:
    setup &OPTIONAL DBURI      setup the pgcharts database
    status                     get the status of the currently running server
    pid                        prints the PID of the server, if running
    stop                       stop the pgcharts web server
    start                      start the pgcharts web server
    register DBURI             register a database
    config                     print current config
    get KEY                    display current value for given configuration key
    set KEY &OPTIONAL VAL      edit configuration variables
    </code>

**Comment by dimitri** [comment]
I guess I would just remove the option from the docs and call it a day, maybe add a `restart` command for ease of use. I'm not sure all the setup is easy to change at runtime... it might be a good idea to add the feature later, but is it really needed?

**Comment by Jacob-Kroeze** [comment]
Start stop makes sense to me. Restart is good enough.

**Comment by dimitri** [comment]
Done removing `reload` from the docs. Did nothing about `restart`. That's how lazy I feel tonight...

**Comment by Jacob-Kroeze** [comment]
+1
